services:
  slurm_exporter:
    build: . # Build the image from the Dockerfile in the current directory
    env_file:
      - .env
    ports:
      - "8000:8000"  # Expose port 8000 to the host 
    restart: unless-stopped